"""empty message

Revision ID: 6adae197c25d
Revises: 0bf52ecae1a2
Create Date: 2022-11-12 16:46:51.495404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6adae197c25d'
down_revision = '0bf52ecae1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_', sa.Column('e', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_', 'e')
    # ### end Alembic commands ###
