"""empty message

Revision ID: 90222c9a3de6
Revises: ecd148178661
Create Date: 2022-11-11 22:43:33.113273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90222c9a3de6'
down_revision = 'ecd148178661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_', sa.Column('username', sa.String(length=30), nullable=False))
    op.drop_column('user_', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('user_', 'username')
    # ### end Alembic commands ###
